### PR TITLE
[ADD]Separated extra code from l10n_fr_fec and put it in newly created module l10n_fr_fec_custom

### PR DESCRIPTION
**Pull request by krunal267**

### CODE REVIEW

**Comment by krunal267** [comment]
Task URL:
https://www.druidoo.io/web#id=1185&action=367&model=project.task&view_type=form&menu_id=237

**Comment by ivantodorovich** [comment]
Hi @krunal267 !

A few changes:

- Please move the fr_fec_custom modules to `intercoop_addons` folder.
`extra_addons` is restricted to OCA modules

- Can we update the standard fr_fec module to add a migration script to automatically install this new module?
It's not great, I know. We shouldn't edit odoo source code. But in this case it's ok, and it would help with the delivery.

**Comment by krunal267** [comment]
> Hi @krunal267 !
> 
> A few changes:
> 
> * Please move the fr_fec_custom modules to `intercoop_addons` folder.
>   `extra_addons` is restricted to OCA modules
> * Can we update the standard fr_fec module to add a migration script to automatically install this new module?
>   It's not great, I know. We shouldn't edit odoo source code. But in this case it's ok, and it would help with the delivery.

Hi Iván,
I pushed the changes you explained.

**Comment by ivantodorovich** [comment]
@krunal267 unfortunately it's not being called on module update. Apparently `post_init_hook` is called after module installation, but not upgrade.

image

Maybe just set `'auto_install': True` in the custom module? 
Or use a migration script instead of a hook

**Comment by ivantodorovich** [comment]
merged https://github.com/AwesomeFoodCoops/odoo-production/pull/991

**Pull request closed without merging**
