### PR TITLE
[ADD] Company name and Email Contact made configurable in a company instead of ir.config_parameter

### PR DESCRIPTION
**Pull request by krunal267**
Task URL:

https://www.druidoo.io/web#id=1607&action=367&model=project.task&view_type=form&menu_id=237

### CODE REVIEW

**Comment by ivantodorovich** [comment]
@krunal267 can we add a migration script to:

- copy old ir.config_parameter values to the new company fields
- remove the old ir.config_parameters (*)

(*) only if they're not used anywhere else in the code of any foodcoops modules, nor email templates, etc.
If you find they're used, please update the code to use the new fields

**Comment by ivantodorovich** [comment]
Also I'd like these fields not to be configurable in the res.company view. But rather in res.config panel.

**Comment by krunal267** [comment]
Okay @ivantodorovich 

noted it.

**Comment by krunal267** [comment]
Hello @ivantodorovich 

Suggested changes are pushed.

**Pull request merged**
