### PR TITLE
12.0 mig l10n fr fec background

### PR DESCRIPTION
**Pull request by krunal267**
Task URL:

https://www.druidoo.io/web#id=811&action=367&model=project.task&view_type=form&menu_id=237

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Thanks @krunal267 !

Travis is failing due to:

```************* Module l10n_fr_fec_background
l10n_fr_fec_background/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
************* Module l10n_fr_fec_background.__manifest__
l10n_fr_fec_background/__manifest__.py:1: [C8102(manifest-required-key), ] Missing required key "license" in manifest file

```

**Comment by ivantodorovich** [comment]
Also can we add some tests? At least to check that the job is created, to have some coverage

**Comment by krunal267** [comment]
Hi @ivantodorovich 

Noted it.

**Comment by ivantodorovich** [comment]
Travis is failing cause of this now:

```
l10n_fr_fec_background/tests/test_l10n_fr_fec_background.py:17:14: E121 continuation line under-indented for hanging indent
l10n_fr_fec_background/tests/test_l10n_fr_fec_background.py:28:14: E121 continuation line under-indented for hanging indent
```

**Pull request merged**
