### PR TITLE
12.0 mig purchase compute order2

### PR DESCRIPTION
**Pull request by krunal267**

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Hi @krunal267 !

Travis is failing because of 2 things:

1. 
`odoo.exceptions.UserError: ("You try to install module 'purchase_compute_order' that depends on module 'product_average_consumption'.\nBut the latter module is not available in your system.", '')
Message not found: 'Modules loaded.'`

That's because this PR depends on https://github.com/druidoo/FoodCoops/pull/5, and I've only just merged it.

Can you please run this to rebase it?

```
git fetch origin 12.0
git rebase origin/12.0
git push --force
```

This will 1) pull codes from github's 12.0 (including product_average_consumption), 2) rebase your commits on the latests changes of 12.0, and force-push here ;)



Also 2.

LINT is failing because of:
```
purchase_compute_order/tests/test_purchase_compute_order.py:6:1: F401 'odoo.fields' imported but unused
purchase_compute_order/tests/test_purchase_compute_order.py:17:31: E231 missing whitespace after ':'
purchase_compute_order/tests/test_purchase_compute_order.py:18:27: E231 missing whitespace after ':'
purchase_compute_order/tests/test_purchase_compute_order.py:64:31: E228 missing whitespace around modulo operator
```

**Comment by krunal267** [comment]
Fail again.
This time it's due to 'purchase_package_qty' module not found.

This module will need **purchase_package_qty** and **product_supplierinfo_discount** modules

**Comment by ivantodorovich** [comment]
Thanks Krunal?

What's the status of those modules? have we migrated them?

If so a good practice when creating PR's is putting this on the comments:
depends on (URL TO PR OF MODULE)

It would help a lot to review!

Anyways, in order to merge this we need to merge the other two modules first.

**Comment by ivantodorovich** [comment]
depends on https://github.com/druidoo/FoodCoops/pull/10 

and also on product_supplierinfo_discount. Only thta this module apparently was merged into another module. Found this on the OCA repository tickets: https://github.com/OCA/purchase-workflow/pull/731

**Comment by ivantodorovich** [comment]
@krunal267 how were you able to test without the missing module?

We need to find a way to integrate this with https://github.com/OCA/purchase-workflow/tree/12.0/purchase_discount (which apparently now holds the old purchase_supplierinfo_discount)

@msdruidoo maybe you want to look

**Comment by ivantodorovich** [comment]
this is the comment where they mention merging `purchase_supplierinfo_discount`: https://github.com/OCA/purchase-workflow/pull/731#pullrequestreview-271853238 leaving this for reference

**Comment by ivantodorovich** [comment]
This is so we don't forget.

Changes were made in this module in 9.0. So, when the time comes, we'll need to forwardport them:
https://github.com/AwesomeFoodCoops/odoo-production/pull/979

**Comment by ivantodorovich** [comment]
Hi @krunal267 !

We intend to use this module for another customer, so we'd like to finish this PR.
I think the only thing missing is resolving the `purchase_supplierinfo_discount` dependency.

In 12.0, this module has been deprecated and its functionality has been merged into `purchase_discount` (this commit, apparently: https://github.com/OCA/purchase-workflow/commit/82536a40eb1064da39f3900f8b4e538c39156bed)

Can you please change the dependency and adapt the code, where necessary (maybe they changed field names or something, when merging the modules..)

Please note that `purchase_package_qty` PR has been merged, so it should be available in 12.0 branch of this repo.

**Comment by ivantodorovich** [comment]
Also, and it's very important.
We need to integrate the changes in this PR: https://github.com/AwesomeFoodCoops/odoo-production/pull/979

You can cherry-pick the 3 commits in order, and migrate them

**Pull request merged**
