### PR TITLE
[ADD]Added a module to update Loss Qty and Opening Qty of a product history

### PR DESCRIPTION
**Pull request by krunal267**
Hi Ivan,

I have added a code to run the update process in the background, but somehow queue.job is not working my side.

So pl. check it out once at your side.

### CODE REVIEW

**Comment by krunal267** [comment]
Task url:
https://www.druidoo.io/web?debug=1#id=979&action=367&model=project.task&view_type=form&menu_id=237

**Comment by ivantodorovich** [comment]
@krunal267 as discussed we only need to remove the product_history_update module :)
Let me know when it's done so I can merge

**Comment by krunal267** [comment]
> @krunal267 as discussed we only need to remove the product_history_update module :)
> Let me know when it's done so I can merge

Hi Ivan, product_history_update is removed now

**Comment by ivantodorovich** [comment]
Thanks!
Superseeded by https://github.com/AwesomeFoodCoops/odoo-production/pull/984 (retargeting to dev branch)

**Pull request closed without merging**
