### PR TITLE
12.0 mig louve_custom_account + coop_account

### PR DESCRIPTION
**Pull request by ajayjaviya**
Task : https://www.druidoo.io/web#id=773&action=361&active_id=28&model=project.task&view_type=form&menu_id=237

### CODE REVIEW

**Comment by ivantodorovich** [comment]
@ajayjaviya can you check why tests are failing?

**Comment by ivantodorovich** [comment]
@ajayjaviya also check task description.
Idea is to merge this into `coop_account` (the same will probably happen with all `louve_*` modules)

**Comment by ivantodorovich** [comment]
I think you can add coop_account migration in this same PR, and merge both modules in a new commit

**Comment by ajayjaviya** [comment]
> @ajayjaviya can you check why tests are failing?

@ivantodorovich : It is due to this module have `reference` and `date_invoice` are required from view and **purchase_package_qty** have test case related to view it save the form so test case from **purchase_package_qty ** module `test_004_check_invoice_line_qty` is fail (https://github.com/druidoo/FoodCoops/blob/12.0/purchase_package_qty/tests/test_purchase_package_qty.py#L86)

**Comment by ivantodorovich** [comment]
> > @ajayjaviya can you check why tests are failing?
> 
> @ivantodorovich : It is due to this module have `reference` and `date_invoice` are required from view and **purchase_package_qty** have test case related to view it save the form so test case from **purchase_package_qty ** module `test_004_check_invoice_line_qty` is fail (https://github.com/druidoo/FoodCoops/blob/12.0/purchase_package_qty/tests/test_purchase_package_qty.py#L86)

I see.

Can you remove that test case, or try to make it work without the `Form()` ?

**Comment by ivantodorovich** [comment]
great! tests fixed @ajayjaviya , don't forget to migrate coop_account and merge the two modules together

**Comment by ivantodorovich** [comment]
Travis is failing mostly because of this, i think:
```
************* Module coop_account.__manifest__
coop_account/__manifest__.py:5: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
************* Module coop_account.report.account_aged_partner_balance
coop_account/report/account_aged_partner_balance.py:34: [E8103(sql-injection), ReportAgedPartnerBalance._get_partner_move_lines] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection
coop_account/report/account_aged_partner_balance.py:34: [E8103(sql-injection), ReportAgedPartnerBalance._get_partner_move_lines] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection
coop_account/report/account_aged_partner_balance.py:34: [E8103(sql-injection), ReportAgedPartnerBalance._get_partner_move_lines] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection
************* Module coop_account.models.account_move_line
coop_account/models/account_move_line.py:148: [E8103(sql-injection), AccountMoveLine.get_wrong_reconciliation_ml] SQL injection risk. Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection
```

also don't forget to merge `louve_custom_account` into `coop_account`. Objective is we have only 1 module: `coop_account`

**Pull request merged**
