### PR TITLE
[ADD] Added 'Cancel' and 'Set to Draft' buttons in Payments

### PR DESCRIPTION
**Pull request by krunal267**
Task URL:

https://www.druidoo.io/web#id=2068&action=367&model=project.task&view_type=form&menu_id=237

### CODE REVIEW

**Comment by ivantodorovich** [comment]
This is a good candidat for a new module in druidoo-addons.

Can you create a module `account_payment_cancel` to implement this?

**Comment by krunal267** [comment]
@ivantodorovich 

https://github.com/druidoo/FoodCoops/blob/12.0/coop_account/view/view_account_payment.xml#L24

We have created a new form view of payment(link above) which is almost same as the original.

I think this view we don't need to create like this, we should inherit the base view. I compared our view with v9 and v12 views, there are some small changes which we can achieve with inheritance.
Like removed widget=selection from some m2o fields, adjusted readonly and invisible attrs.

I found that cancel and set to draft buttons are already there in odoo, 'Set to Draft' button is in original view, and if we install account_cancel, it adds the 'Cancel' button.

**Comment by ivantodorovich** [comment]
Wow, a new view. It's crap.. But yeah, originally there were many views like this in 9.0 :/

Yes, please change it to use inheritance.

Also, since we're on the topic. 
Can we somehow list all views in foodcoops modules that are like this? (don't know if it's possible)
We should almost never replace a view, and I want to make sure we don't have this issue in other places.

**Comment by krunal267** [comment]
Okay @ivantodorovich 

I will do it.

**Comment by krunal267** [comment]
@ivantodorovich 

Changes are pushed. :)

**Pull request merged**
